myapp/urls.py
from django.urls import path
from . import views


app_name = 'myapp'

# automatically prepends with /
urlpatterns = [
    path('hello/', views.index),
    path('products/', views.products, name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/update/<int:pk>/', views.ProductUpdateView.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete_product'),
    path('products/mylistings', views.my_listings, name='mylistings'),
    path('success/', views.PaymentSuccessView.as_view(), name='success'),
    path('failed/', views.PaymentFailedView.as_view(), name='failed'),
    path('api/checkout-session/<id>', views.create_checkout_session, name='api_checkout_session'), # not an actual view. Just an API call in the backend
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# automatically prepends with /
urlpatterns = [
    path('/', RedirectView.as_view(pattern_name='myapp:products', permanent=False)),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

# automatically prepends with /
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/create/', views.create_profile),
    path('seller/<int:id>/', views.seller_profile, name='seller_profile'),
]

myapp/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Products(models.Model):   
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myapp:products')
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=20)
    price = models.IntegerField()
    desc = models.CharField(max_length=100)
    image = models.ImageField(blank=True, upload_to='images', default='404.png')

class orderDetail(models.Model):
    customer_username = models.CharField(max_length=30)
    product = models.ForeignKey(to='Products', on_delete=models.PROTECT) # protects the field even if the actual field is deleted
    amount = models.IntegerField()
    checkout_session_id = models.CharField(max_length=200) 
    payment_intent = models.CharField(max_length=200, null=True)
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True) # adds current dateNtime automatically
    updated_on = models.DateTimeField(auto_now_add=True)

myapp/views.py
from asyncio import create_subprocess_exec, create_subprocess_shell
from pipes import Template
from time import sleep
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from .models import Products, orderDetail
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator

from django.urls import reverse, reverse_lazy
from django.http.response import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404
from django.conf import settings as s
from django.views.decorators.csrf import csrf_exempt
import stripe

# Create your views here.
def index(request):
    return render(request, 'myapp/base.html')

def products(request):
    page_obj = productss = Products.objects.all()

    product_name = request.GET.get('product_name')
    
    if (product_name):
        page_obj = productss.filter(name__icontains=product_name)
    
    paginator = Paginator(page_obj, 3) # Paginates the objects by 3
    page_num = request.GET.get('page')  # Gets the page number from the request (.../?page=x)
    page_obj = paginator.get_page(page_num) # Gets the items within that page

    context = {
        'page_obj': page_obj,
    }

    return render(request, 'myapp/index.html', context)

# class based view
class ProductListView(ListView):
    model = Products
    template_name = 'myapp/index.html'
    context_object_name = 'products'
    paginate_by = 4

def product_detail(request, id):
    products = Products.objects.get(id=id)

    context = {
        'product': products
    }
    return render(request, 'myapp/detail.html', context)

# class based view
class ProductDetailView(DetailView):
    model = Products
    template_name = 'myapp/detail.html'
    context_object_name = 'product'
    
    pk_url_kwarg = 'pk' #kwarg is actually the id of the product for which the payment has to be done

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs) #gets context data
        context['stripe_publishable_key'] = s.STRIPE_PUBLIC_KEY   # modifies context
        return context

@login_required
def add_product(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        
        try:
            image = request.FILES['upload']
            product = Products(name=name, price=price, desc=desc, image=image, user=user)
        except Exception as e:
            print(e)
            product = Products(name=name, price=price, desc=desc, user=user)

        product.save()

        return redirect('/myapp/products')

    return render(request, 'myapp/addproduct.html')

# class based view
class ProductCreateView(CreateView):
    model = Products
    fields = ['user', 'name', 'price', 'desc', 'image']
    

def update_product(request, id):
    product = Products.objects.get(id=id)

    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES['upload']
        product.save()

        return redirect('/myapp/products')

    context = {
        'product': product
    }
    return render(request, 'myapp/updateprod.html', context)

class ProductUpdateView(UpdateView):
    model = Products
    fields = ['user', 'name', 'desc', 'price', 'image']
    template_name = 'myapp/prod_update_form.html'

def delete_product(request, id):
    product = Products.objects.get(id=id)
    context = {
        'product': product,
    }

    if (request.method == 'POST'):
        product.delete()
        return redirect('/myapp/products')
    
    return render(request, 'myapp/deleteprod.html', context=context)

class ProductDeleteView(DeleteView):
    model = Products
    template_name = 'myapp/prod_delete.html'
    success_url = reverse_lazy('myapp:products')

@login_required
def my_listings(request):
    products = Products.objects.filter(user=request.user)
    context = {
        'products': products
    }
    return render(request, 'myapp/mylistings.html', context)

@csrf_exempt
def create_checkout_session(request, id):
    product = get_object_or_404(Products, pk=id)
    stripe.api_key = s.STRIPE_SECRET_KEY

    checkout_session = stripe.checkout.Session.create(
        customer_email = request.user.email,
        payment_method_types = ['card'],
        line_items = [
            # Item1
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': product.name,
                    },
                    'unit_amount': int(product.price * 100),
                },
                'quantity': 1,
            }
        ],
        mode = 'payment', # one-time payment OR subscription

        success_url = request.build_absolute_uri(reverse('myapp:success')) + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url = request.build_absolute_uri(reverse('myapp:failed')),
    )

    order = orderDetail()
    order.customer_username = request.user.username
    order.product = product
    order.checkout_session_id = checkout_session['id']
    order.amount = int(product.price * 100)
    order.save()

    return JsonResponse({'sessionId': checkout_session.id})

class PaymentSuccessView(TemplateView):
    template_name = 'myapp/success.html'

    def get(self, request, *args, **kwargs):

        sessionId = request.GET.get('session_id') # gets session_id from URL (.../?sessoin_id=xxx)
        
        if not sessionId:
            return HttpResponseNotFound()
        
        session = stripe.checkout.Session.retrieve(sessionId)
        stripe.api_key = s.STRIPE_SECRET_KEY

        order = get_object_or_404(orderDetail, checkout_session_id=sessionId) # gets the order by matching 'strip_payment_intent' field
        order.has_paid = True
        order.payment_intent = session.payment_intent
        order.save()

        return render(request, self.template_name)

class PaymentFailedView(TemplateView):
    template_name = 'myapp/failed.html'

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html'%}
{% block content%}

<section id="addproduct" class="container mx-auto max-w-6xl p-6">

    <div class="mt-8">
        <h1 class="text-3xl font-bold">
            <span class="text-4xl text-gray-500">+</span>
            Add Product
        </h1>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="flex flex-col shadow space-y-8 rounded shadow-lg mt-6 p-10 w-1/2 outline outline-2 outline-gray-400">

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Name</h2>
                <input class="shadow appearance-none border rounded p-2 w-1/2 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600" type="text" name="name" id="name" placeholder="Enter product name">
            </div>

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Price</h2>
                <input class="shadow appearance-none border rounded p-2 w-1/2 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600" type="text" name="price" id="price" placeholder="Enter product price">
            </div>

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Description</h2>
                <input class="shadow appearance-none border rounded p-2 w-1/2 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600" type="text" name="desc" id="desc" placeholder="Enter product description">
            </div>

            <div>
                <h2 class="text-lg font-bold text-gray-800">Product Image</h2>
                <input class="mt-4" type="file" accept="image/*" name="upload" id="upload" value="Browse..">
            </div>
            
            <div class="flex justify-center">
                <input  class=" text-white p-2 w-full rounded-full bg-brightRed outline outline-1 outline-gray-300 hover:bg-brightRedLight" type="submit" name="Add Product" value="Add Product" id="addp">
            </div>
            

        </div>
    </form>
</section>


{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/main.css'%}">
    <title>Django Landing Page</title>
</head>
<body>
    <nav class="shadow-lg">
        <div class="flex container mx-auto max-w-6xl px-6 items-center justify-between">
            <!-- Logo and Name -->
            <a href="{% url 'myapp:products' %}">
                <div class="flex space-x-1 md:space-x-3">
                    <img src="{% static 'img/bag.png'%}" class="h-8" alt="">
                    <div class="text-3xl font-semibold">
                        Buy&Sell
                    </div>
                </div>
            </a>
            

            <!-- NavMenu Options -->
            <div class="flex items-center space-x-12">

                <div class="flex flex-row space-x-10 font-medium">
                    <a href="{% url 'myapp:products' %}" class="text-lg border-b-4 py-6 border-orange-300">Home</a>
                    <a href="{% url 'myapp:mylistings' %}" class="text-lg py-6">Products</a>
                    <a href="" class="text-lg py-6">About</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}" class="text-lg py-6">Logout</a>
                    {% else %}
                        <a href="{% url 'users:login' %}" class="text-lg py-6">Login</a>
                    {% endif %}                
                </div>
                
                {% if user.is_authenticated %}
                <div class="text-lg py-7">
                    <a class="" href="{% url 'users:profile' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 " viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd" />
                        </svg>
                    </a>
                </div>
                {% endif %}
            </div>

            <a href="{% url 'myapp:add_product' %}">
                <div class="rounded-full border border-orange-400 px-4 py-2 text-orange-500 hover:text-white hover:bg-orange-500">
                    Post an Ad
                </div>
            </a>
            
            
            
        </div>
    </nav>

    {% block content %}

    {% endblock %}
</body>
</html>

myapp/templates/myapp/deleteprod.html
{% extends 'myapp/base.html' %}
{% block content %}
<section class="container mx-auto max-w-6xl p-8 ">
    <div class="h1 text-3xl font-bold mb-10 mt-6">
        Are you sure, you want to delete this Product?
    </div>
    <div class="flex flex-row space-x-12 p-8 items-center shadow border w-3/5">
        <div class="w-1/3">
            <img src="{{product.image.url}}" class="" alt="">
        </div>
        <div class="flex flex-col py-4 space-y-2">
            <div class="font-bold text-3xl">{{product.name}}</div>
            <div class="font-semibold text-3xl text-orange-500">$ {{product.price}}</div>
            <div class=" text-gray-500">{{product.desc}}</div>
        </div>
    </div>

    <form method="POST">
    {% csrf_token %}
    <div class="flex ">
        <div class="w-1/2"></div>
        <div class="flex flex-row p-6 justify-center space-x-6 bg mt-4 ml-4">
            <div class="border border-orange-500 rounded-full text-orange-500 px-8 py-2">
                <a href="{% url 'myapp:products' %}">Cancel</a>
            </div>
            <div class="bg-orange-500 rounded-full text-white px-8 py-2 ">
                <input type="submit" value="Confirm" class="">
            </div>
        </div>
        
    </div>
    </form>

</section>


{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block content %}
<section class="container mx-auto max-w-6xl p-8 ">
    <div class="flex flex-row space-x-12 p-8 items-start ">
        <div class="w-1/3">
            <img src="{{product.image.url}}" class="" alt="">
        </div>
        <div class="flex flex-col mt-10 py-4 space-y-3">
            <div class="font-bold text-3xl">{{product.name}}</div>
            <div class="font-semibold text-3xl text-orange-500">$ {{product.price}}</div>
            <div class="text-xl text-gray-400">{{product.desc}}</div>
            <div class="py-2"></div>
            <div class="text-xl text-gray-500">
                 > Posted by: 
                <a href="{% url 'users:seller_profile' product.user.id %}" class="hover:underline">
                    <span class="font-bold">{{product.user}}</span> 
                </a>
            </div>
            
        </div>
        
    </div>
    <div class="flex -mt-10">
        <div class="w-1/2"></div>
        <div class="flex bg-gray-300 ml-16">
            <button class="bg-aquamarine px-4 py-2 rounded text-white hover:bg-white hover:text-aquamarine hover:outline hover:outline-1 hover:outline-aquamarine" id="checkout" >Checkout</button>
        </div>
    </div>

    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">

        var stripe = Stripe('{{ stripe_publishable_key }}')
        var checkoutButton = document.getElementById('checkout')
        checkoutButton.addEventListener('click', function(){
            fetch("{% url 'myapp:api_checkout_session' id=product.id %}", {method:'POST',})
            .then(function(response){
                return response.json()
            })
            .then(function(session){
                return stripe.redirectToCheckout({sessionId:session.sessionId})
            })
            .then(function(result){
                if (result.error){
                    alert(result.error.message)
                }
            })
            .catch(function(error){
                console.error('Error:', error)
            })
        })

    </script>

</section>


{% endblock %}

myapp/templates/myapp/failed.html
{% extends 'myapp/base.html' %}
{% block content %}
    <p class="lead font-semibold">Oops! Payment Failed <span class="text-green-500">successfully</span>!</p>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load pagination_tags %}

{% block content%}

<!-- Hero Section -->
<main id="Hero">
    <div class="container mx-auto max-w-6xl mt-10 px-6">
        <div class="text-center text-4xl font-extrabold md:text-6xl md:text-left">
            Premium Products
            <span class="block">
                <span class="text-orange-500 ">Non-Premium Prices</span>
            </span>
        </div>
        
        <p class="text-center text-sm my-6 text-gray-500 md:text-base md:text-left">
            Get the best quality used products across the globe. Free Shipping.
        </p>

    </div>
</main>

<section id="products">
    <div class="container mx-auto max-w-6xl p-6 mb-10">
        <h2 class="text-gray-500 text-3xl p-10 text-center font-normal">Recent Products</h2>

        <!-- Search Bar -->
        <div class="flex justify-center mb-10">
            <div class="flex flex-row items-center space-x-3 border border-gray-300 rounded w-1/3 px-4 py-2">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
                <form method="GET">
                    <input class="text-gray-600" type="text" style="outline: none;" placeholder="Search products ...."  id="product_name" name="product_name">
                </form>
            </div>
        </div>
        
        

        <div class="grid grid-cols-1 md:grid-cols-3 gap-5 mt-10">
            {% for product in page_obj %}
            <!-- Card 1 -->
            <a href="{% url 'myapp:product_detail' product.id %}">
                <div class="flex flex-col items-center rounded overflow-hidden shadow-lg space-y-1 pb-4">
                    <img src="{{product.image.url}}" alt="img" class="w-full">
                    <span class="font-bold text-2xl"> {{product.name}} </span>
                    <span class="font-bold text-xl text-orange-500">$ {{product.price}} </span>
                    <span class="text-base text-gray-400"> {{product.desc}} </span>
                    <span class="text-base text-gray-600"> Posted by: <span class="font-bold">{{product.user}}</span> </span>
                </div>
            </a>
            {% endfor %}
        </div>

        <!-- Pagination -->
        <div class="flex items-center my-16 justify-center space-x-3">
            {% if page_obj.has_previous %}
            <div class="flex">
                <h1></h1>
                <a href="?{% url_replace request 'page' 1 %}" class="shadow p-2 text-aquamarine">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M11 19l-7-7 7-7m8 14l-7-7 7-7" />
                    </svg>
                </a>
                <a href="?{% url_replace request 'page' page_obj.previous_page_number %}" class="shadow p-2 text-aquamarine">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
                    </svg>
                </a>
            </div>
            {% endif %}

            <div class="text-gray-600">
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </div>

            {% if page_obj.has_next %}
            <div class="flex">
                <a href="?{% url_replace request 'page' page_obj.next_page_number %}" class="shadow p-2 text-aquamarine">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                    </svg>
                </a>
                <a href="?{% url_replace request 'page' page_obj.paginator.num_pages %}" class="shadow p-2 text-aquamarine">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                    </svg>
                </a>
            </div>
            {% endif %}
        </div>

    </div>
    
</section>

    


{% endblock %}

myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html'%}
{% block content %}
<section id="myproducts" class="p-6 mx-auto max-w-6xl container">
    <div class="flex items-center space-x-6">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
          </svg>
        <h1 class="text-3xl font-bold my-8 ">My Products</h1>
    </div>

    {% for product in products %}
    <div class="flex flex-row space-x-16 p-8 items-center shadow-lg w-4/5">
        <div class="">
            <img src="{{product.image.url}}" class="h-40 w-40" alt="">
        </div>
        <div class="flex flex-col mt-10 py-4 space-y-3 w-2/5">
            <div class="font-bold text-lg">{{product.name}}</div>
            <div class="font-semibold text-lg text-redOrange">$ {{product.price}}</div>
            <div class="text-lg text-gray-400">{{product.desc}}</div>
            <div class="py-2"></div>
        </div>
        <div class="flex flex-col space-y-8">
            <a href="{% url 'myapp:update_product' product.id %}" class="button rounded-full px-10 py-2 text-aquamarine border border-aquamarine items-center hover:bg-aquamarine hover:text-white">Edit</a>
            <a href="{% url 'myapp:delete_product' product.id %}" class="button rounded-full px-8 py-2 text-aquamarine border border-aquamarine items-center hover:bg-aquamarine hover:text-white">Delete</a>
        </div>
    </div>
    {% endfor %}
</section>
{% endblock %}

myapp/templates/myapp/prod_delete.html
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you wanna delete {{object}} ?</p>
    <input type="submit" value="confirm" name="" id="">

</form>

myapp/templates/myapp/prod_update_form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

myapp/templates/myapp/products_form.html
{% extends 'myapp/base.html'%}
{% block content%}

<section id="addproduct" class="container mx-auto max-w-6xl p-6">

    <div class="mt-8">
        <h1 class="text-3xl font-bold">
            <span class="text-4xl text-gray-500">+</span>
            Add Product
        </h1>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="flex flex-col shadow space-y-8 rounded shadow-lg mt-6 p-10 w-1/2 outline outline-2 outline-gray-400">

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Name</h2>
                <div class="shadow appearance-none border rounded p-2 w-2/3 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600">{{form.name}}</div>
            </div>

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Price</h2>
                <div class="shadow appearance-none border rounded p-2 w-2/3 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600">{{form.price}}</div>
            </div>

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Description</h2>
                <div class="shadow appearance-none border rounded p-2 w-2/3 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600">{{form.desc}}</div>
            </div>

            <div>
                <h2 class="text-lg font-bold text-gray-800">Product Image</h2>
                <div class="mt-4">
                {{form.image}}
                </div>
            </div>

            <div>
                <div class="hidden mt-4">
                    {{form.user}}
                </div>
            </div>
            
            <div class="flex justify-center">
                <input  class=" text-white p-2 w-full rounded-full bg-brightRed outline outline-1 outline-gray-300 hover:bg-brightRedLight" type="submit" name="Add Product" value="Add Product" id="addp">
            </div>
            

        </div>
    </form>
</section>


{% endblock %}

myapp/templates/myapp/success.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="container mx-auto max-w-6xl mt-10">
    <p class="text-3xl p-6 con font-semibold">Wohoo! Order has been placed <span class="text-green-500">successfully</span>!</p>    
</div>
    
{% endblock %}

myapp/templates/myapp/updateprod.html
{% extends 'myapp/base.html'%}
{% block content%}

<section id="addproduct" class="container mx-auto max-w-6xl p-6">

    <div class="mt-8">
        <h1 class="text-3xl font-bold">
            <span class="text-4xl text-gray-500">></span>
            Update Product
        </h1>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="flex flex-col shadow space-y-8 rounded shadow-lg mt-6 p-10 w-1/2 outline outline-2 outline-gray-400">

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Name</h2>
                <input class="shadow appearance-none border rounded p-2 w-1/2 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600" type="text" name="name" id="name" value="{{ product.name }}">
            </div>

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Price</h2>
                <input class="shadow appearance-none border rounded p-2 w-1/2 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600" type="text" name="price" id="price" value="{{ product.price }}">
            </div>

            <div class="flex flex-col space-y-2">
                <h2 class="text-lg font-bold text-gray-800">Product Description</h2>
                <input class="shadow appearance-none border rounded p-2 w-1/2 focus:outline focus:outline-2 focus:outline-blue-500 text-gray-600" type="text" name="desc" id="desc" value="{{ product.desc }}">
            </div>

            <img class="h-20 w-20" src="{{product.image.url}}" alt="">

            <div>
                <h2 class="text-lg font-bold text-gray-800">Product Image</h2>
                <input class="mt-4" type="file" accept="image/*" name="upload" id="upload" value="Browse..">
            </div>
            
            <div class="flex justify-center">
                <input  class=" text-white p-2 w-full rounded-full bg-brightRed outline outline-1 outline-gray-300 hover:bg-brightRedLight" type="submit" name="Update Product" value="Update Product" id="addp">
            </div>
            

        </div>
    </form>
</section>


{% endblock %}